LITwillio/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_Classification__c</fullName>
        <description>Field value of this field is set from account before save flow, based on Total Customer Spend field.This field’s value is restricted to 3 possible values to maintain data integrity</description>
        <label>Customer Classification</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GOLD</fullName>
                </value>
                <value>
                    <fullName>SILVER</fullName>
                </value>
                <value>
                    <fullName>BRONZE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Customer_Spend__c</fullName>
        <description>Store sum of the amount on closed-won opportunities for an Account. This field is set by after save flow on account.</description>
        <label>Total Customer Spend</label>
        <summarizedField>Opportunity.Amount</summarizedField>
        <summaryFilterItems>
            <field>Opportunity.StageName</field>
            <operation>equals</operation>
            <value>Closed Won</value>
        </summaryFilterItems>
        <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LITwillio/objects/Customer_Classification_Configuration__mdt.object
<CustomObject>
    <description>This custom metadata holds lowest value required for each of the customer classification</description>
    <fields>
        <fullName>Lowest_Amount_For_Bronze_Classification__c</fullName>
        <description>If Total Customer Spend of account is greater than or equal to this value, Account will be classified as Bronze</description>
        <inlineHelpText>If Total Customer Spend of account is greater than or equal to this value, Account will be classified as Bronze</inlineHelpText>
        <label>Lowest Amount For Bronze Classification</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lowest_Amount_For_Gold_Classification__c</fullName>
        <description>If Total Customer Spend of account is greater than or equal to this value, Account will be classified as gold</description>
        <inlineHelpText>If Total Customer Spend of account is greater than or equal to this value, Account will be classified as gold</inlineHelpText>
        <label>Lowest Amount For Gold Classification</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lowest_Amount_For_Silver_Classification__c</fullName>
        <description>If Total Customer Spend of account is greater than or equal to this value, Account will be classified as SILVER</description>
        <inlineHelpText>If Total Customer Spend of account is greater than or equal to this value, Account will be classified as SILVER</inlineHelpText>
        <label>Lowest Amount For Silver Classification</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Customer Classification Configuration</label>
    <pluralLabel>Customer Classification Configurations</pluralLabel>
</CustomObject>

LITwillio/classes/AccountTotalSpendAndClassificationTest.cls
@isTest
public class AccountTotalSpendAndClassificationTest{
    
    @testSetup static void generateAccountAndOpportunties() {
        // Most of the org will have test data factory framework and utility method exposed to create test data
        // Here direcly creating record as test data framework is not present in this Developer demo org
        Account customer = new Account( Name ='Test Acc 1',Phone = '0123456789');
        insert customer ;
        
        Customer_Classification_Configuration__mdt classificationConfig = Customer_Classification_Configuration__mdt.getInstance('Total_Customer_Spend_Account_Config');
        Decimal amountWithNoClassification = classificationConfig.Lowest_Amount_For_Bronze_Classification__c - 1;
        
        List<opportunity> opportunities = new List<Opportunity>();
        opportunities.add(new Opportunity(Name='Test Opp1',
                                          AccountId=customer.Id,
                                          Amount=amountWithNoClassification ,
                                          StageName='Closed Won',
                                          CloseDate=System.today()));
        opportunities.add(new Opportunity(Name='Bronze Status Opp',
                                          AccountId=customer.Id,
                                          Amount=classificationConfig.Lowest_Amount_For_Bronze_Classification__c ,
                                          StageName='Proposal/Price Quote',
                                          CloseDate=System.today()));
        opportunities.add(new Opportunity(Name='Silver Status Opp',
                                          AccountId=customer.Id,
                                          Amount=classificationConfig.Lowest_Amount_For_Silver_Classification__c,
                                          StageName='Proposal/Price Quote',
                                          CloseDate=System.today()));
        opportunities.add(new Opportunity(Name='Gold Status Opp',
                                          AccountId=customer.Id,
                                          Amount=classificationConfig.Lowest_Amount_For_Gold_Classification__c,
                                          StageName='Proposal/Price Quote',
                                          CloseDate=System.today()));
        insert opportunities;
    }
    @isTest private static void testBlankClassification(){
         Customer_Classification_Configuration__mdt classificationConfig = Customer_Classification_Configuration__mdt.getInstance('Total_Customer_Spend_Account_Config');
         Decimal amountWithNoClassification = classificationConfig.Lowest_Amount_For_Bronze_Classification__c - 1;
        
         Account customer = [SELECT Customer_Classification__c,Total_Customer_Spend__c FROM Account WHERE Name='Test Acc 1'];
         System.assertEquals(amountWithNoClassification ,customer.Total_Customer_Spend__c,'Only 1 Opportunity is closed won');
         System.assertEquals(null,customer.Customer_Classification__c,'Total Spend is below the threshold for account classification');
    }
    @isTest private static void testBronzeClassification(){
        Customer_Classification_Configuration__mdt classificationConfig = Customer_Classification_Configuration__mdt.getInstance('Total_Customer_Spend_Account_Config');
        Decimal amountWithNoClassification = classificationConfig.Lowest_Amount_For_Bronze_Classification__c - 1;
        
        Account customer = [SELECT Customer_Classification__c,Total_Customer_Spend__c FROM Account WHERE Name='Test Acc 1'];
         System.assertEquals(amountWithNoClassification ,customer.Total_Customer_Spend__c,'Only 1 Opportunity is closed won');
         System.assertEquals(null,customer.Customer_Classification__c,'Total Spend is below the threshold for account classification');
         
         Opportunity opp = [SELECT Id,StageName FROM Opportunity WHERE Name='Bronze Status Opp'];
         opp.stageName = 'closed won';
         update opp ;
         
         customer = [SELECT Customer_Classification__c,Total_Customer_Spend__c FROM Account WHERE Name='Test Acc 1'];
         System.assertEquals(amountWithNoClassification  + classificationConfig.Lowest_Amount_For_Bronze_Classification__c,
                             customer.Total_Customer_Spend__c,'Now 2 Opportunities are closed won, classification should change to bronze.');
         System.assertEquals('BRONZE',customer.Customer_Classification__c,'Total Spend quailify for Bronze classification');
    }
     @isTest private static void testSilverClassification(){
          Customer_Classification_Configuration__mdt classificationConfig = Customer_Classification_Configuration__mdt.getInstance('Total_Customer_Spend_Account_Config');
          Decimal amountWithNoClassification = classificationConfig.Lowest_Amount_For_Bronze_Classification__c - 1;
        
         Account customer = [SELECT Customer_Classification__c,Total_Customer_Spend__c FROM Account WHERE Name='Test Acc 1'];
         System.assertEquals(amountWithNoClassification ,customer.Total_Customer_Spend__c,'Only 1 Opportunity is closed won');
         System.assertEquals(null,customer.Customer_Classification__c,'Total Spend is below the threshold for account classification');
         
         Opportunity opp = [SELECT Id,StageName FROM Opportunity WHERE Name='Silver Status Opp'];
         opp.stageName = 'closed won';
         update opp ;
         
         customer = [SELECT Customer_Classification__c,Total_Customer_Spend__c FROM Account WHERE Name='Test Acc 1'];
         System.assertEquals(amountWithNoClassification  + classificationConfig.Lowest_Amount_For_Silver_Classification__c,
                             customer.Total_Customer_Spend__c,'Now 2 Opportunities are closed won, classification should change to Silver.');
         System.assertEquals('SILVER',customer.Customer_Classification__c,'Total Spend quailify for Silver classification');
    }
     @isTest private static void testGoldClassification(){
        Customer_Classification_Configuration__mdt classificationConfig = Customer_Classification_Configuration__mdt.getInstance('Total_Customer_Spend_Account_Config');
        Decimal amountWithNoClassification = classificationConfig.Lowest_Amount_For_Bronze_Classification__c - 1;
        
        Account customer = [SELECT Customer_Classification__c,Total_Customer_Spend__c FROM Account WHERE Name='Test Acc 1'];
         System.assertEquals(amountWithNoClassification, customer.Total_Customer_Spend__c,'Only 1 Opportunity is closed won');
         System.assertEquals(null,customer.Customer_Classification__c,'Total Spend is below the threshold for account classification');
         Test.startTest();
             Opportunity opp = [SELECT Id,StageName FROM Opportunity WHERE Name='Gold Status Opp'];
             opp.stageName = 'closed won';
             update opp ;
         Test.stopTest();
         customer = [SELECT Customer_Classification__c,Total_Customer_Spend__c FROM Account WHERE Name='Test Acc 1'];
         System.assertEquals(amountWithNoClassification + classificationConfig.Lowest_Amount_For_Gold_Classification__c,
                             customer.Total_Customer_Spend__c,'Now 2 Opportunities are closed won, classification should change to Gold.');
         System.assertEquals('GOLD',customer.Customer_Classification__c,'Total Spend quailify for Gold classification');
        
    }
}